--46
select EMP_FNAME, EMP_LNAME, EMP_EMAIL
from LGEMPLOYEE
where EMP_HIREDATE between '2001-01-01' AND  '2010-12-31'
order by EMP_LNAME, EMP_FNAME;

--47
select EMP_FNAME,EMP_LNAME, EMP_PHONE, EMP_TITLE, DEPT_NUM
from LGEMPLOYEE
where DEPT_NUM=300 or EMP_TITLE='CLERK 1'
order by EMP_LNAME, EMP_FNAME

--48
select LGEMPLOYEE.EMP_NUM, EMP_LNAME, EMP_FNAME,  SAL_FROM, SAL_END, SAL_AMOUNT 
from LGEMPLOYEE, LGSALARY_HISTORY
where LGEMPLOYEE.EMP_NUM = 83731 or LGEMPLOYEE.EMP_NUM = 83745 or LGEMPLOYEE.EMP_NUM = 84039
order by LGEMPLOYEE.EMP_NUM, SAL_FROM


--49
select distinct CUST_FNAME, CUST_LNAME, CUST_STREET, CUST_CITY, CUST_STATE, CUST_ZIP
from LGCUSTOMER, LGPRODUCT
where LGPRODUCT.PROD_CATEGORY = 'Top Coat' AND LGPRODUCT.BRAND_ID=23
order by  CUST_STATE, CUST_LNAME, CUST_FNAME

--50
select LGEMPLOYEE.EMP_NUM, EMP_LNAME, EMP_EMAIL, EMP_TITLE, DEPT_NAME
from LGEMPLOYEE, LGDEPARTMENT
where EMP_TITLE like '%Associate%'
order by DEPT_NAME, EMP_TITLE

--51
select BRAND_NAME, count(PROD_SKU) as NUMPRODUCTS
from LGBRAND, LGPRODUCT
where LGBRAND.BRAND_ID=LGPRODUCT.BRAND_ID
group by BRAND_NAME

--52
select PROD_CATEGORY, count(PROD_SKU) as NUMPRODUCTS
from LGPRODUCT
where PROD_BASE='Water'
group by PROD_CATEGORY

--53
select PROD_BASE, PROD_TYPE, count(PROD_SKU) as NUMPRODUCTS
from LGPRODUCT
group by PROD_BASE, PROD_TYPE

--54
select BRAND_ID, sum(PROD_QOH) as TOTALINVENTORY
from LGPRODUCT
group by BRAND_ID
order by BRAND_ID desc

--55
select LGBRAND.BRAND_ID, BRAND_NAME, AVG(PROD_PRICE) as AVGPRICE
from LGBRAND, LGPRODUCT
where LGBRAND.BRAND_ID = LGPRODUCT.BRAND_ID
group by LGBRAND.BRAND_ID, BRAND_NAME

--56
select LGDEPARTMENT.DEPT_NUM, max(EMP_HIREDATE) as MOSTRECENT
from LGDEPARTMENT, LGEMPLOYEE
where LGDEPARTMENT.DEPT_NUM = LGEMPLOYEE.DEPT_NUM
group by LGDEPARTMENT.DEPT_NUM 

--57
select LGEMPLOYEE.EMP_NUM, EMP_FNAME, EMP_LNAME, max(SAL_AMOUNT) as LARGESTSALARY
from LGEMPLOYEE, LGSALARY_HISTORY
where LGEMPLOYEE.EMP_NUM = LGSALARY_HISTORY.EMP_NUM AND DEPT_NUM=200
group by LGEMPLOYEE.EMP_NUM, EMP_FNAME, EMP_LNAME, LGSALARY_HISTORY.SAL_AMOUNT

--58
select LGCUSTOMER.CUST_CODE, CUST_FNAME, CUST_LNAME, sum(INV_TOTAL) as TOTALINVOICES
from LGCUSTOMER, LGINVOICE
where LGCUSTOMER.CUST_CODE = LGINVOICE.CUST_CODE 
group by LGCUSTOMER.CUST_CODE, CUST_FNAME, CUST_LNAME, INV_TOTAL
order by INV_TOTAL

--59
select LGDEPARTMENT.DEPT_NUM, DEPT_NAME, DEPT_PHONE, LGEMPLOYEE.EMP_NUM, EMP_LNAME, EMP_TITLE
from LGDEPARTMENT, LGEMPLOYEE
where EMP_TITLE like '%MANAGER%' AND LGDEPARTMENT.DEPT_NUM = LGEMPLOYEE.DEPT_NUM
order by DEPT_NAME

--60
select LGSUPPLIES.VEND_ID, LGVENDOR.VEND_NAME, LGBRAND.BRAND_NAME, count(LGPRODUCT.PROD_SKU) as NUMPRODUCTS
from LGSUPPLIES, LGBRAND, LGVENDOR, LGPRODUCT
where LGVENDOR.VEND_ID=LGSUPPLIES.VEND_ID AND LGSUPPLIES.PROD_SKU = LGPRODUCT.PROD_SKU AND LGPRODUCT.BRAND_ID = LGBRAND.BRAND_ID
group by LGSUPPLIES.VEND_ID, LGBRAND.BRAND_ID, LGVENDOR.VEND_NAME, LGBRAND.BRAND_NAME
order by VEND_NAME, BRAND_NAME

--61
select LGEMPLOYEE.EMP_NUM, EMP_LNAME, EMP_FNAME, sum(LGINVOICE.INV_TOTAL) as TOTALINVOICES
from LGEMPLOYEE, LGINVOICE
where LGEMPLOYEE.EMP_NUM = LGINVOICE.EMPLOYEE_ID
group by LGEMPLOYEE.EMP_NUM, LGEMPLOYEE.EMP_LNAME, LGEMPLOYEE.EMP_FNAME
order by EMP_LNAME, EMP_FNAME

--62
select max(avg(PROD_PRICE)) as LARGESTAVERAGE
from LGPRODUCT
group by BRAND_ID

--63
select LGBRAND.BRAND_ID, BRAND_NAME, BRAND_TYPE, avg(PROD_PRICE) as AVGPRICE
from LGBRAND, LGPRODUCT
where LGBRAND.BRAND_ID = LGPRODUCT.BRAND_ID

--64
select


